<?php
 
                /***************************************************************************
		                                extension.inc
		                             -------------------
		    begin                : February Mon 4 2003
		    copyright            : (C) 2003 The nm114.net Group
		    email                : brgd@263.net
		
		    $Id: head.php,v 0.1 2003/03/08 brgd $
		
		 ***************************************************************************/

if ( !defined('IN_MYY') )
{
	 die("对不起！无效访问。<p>Sorry! This accessing is not valid! Try again.");
}

$myyEx = "php";

?>